# -*- coding: utf-8 -*-
"""AIDI 2003 ASS#3 (ADEKUNLE OLOMOLA).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D5Qb2kRCmnMKl_IhYZsdyRqSYQAtOsak
"""

!pip install transformers
!pip install gradio

# Import necessary libraries
from transformers import pipeline

# Initialize a translation pipeline
translator = pipeline("translation_en_to_de", model="t5-base")

# Translate English text to German
translation = translator("I love programming")[0]['translation_text']
print(translation) # Output: Ich liebe Programmieren.

# Import necessary libraries
import gradio as gr
from transformers import pipeline

# Initialize a translation pipeline
translator = pipeline("translation_en_to_de", model="t5-base")

def translate(text):
    # Translate English text to German
    translation = translator(text)[0]['translation_text']
    return translation

iface = gr.Interface(fn=translate,
                     inputs=gr.inputs.Textbox(lines=2, placeholder='Text to translate...'),
                     outputs="text")

iface.launch()

